# Generated by Django 5.0.4 on 2024-04-20 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainAPP', '0001_initial'),
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_answer', models.FileField(upload_to='User_answers/')),
                ('status', models.IntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'In progress')], default=2)),
                ('teacher_response', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentApp.applicant')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Examiners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.subjectteacher')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.exam')),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.examiners')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.subjectteacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('question_file', models.FileField(upload_to='Interview_questions/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainAPP.subject')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.applicant')),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.interviewer')),
                ('interview_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.interviewquestionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interviewer',
            name='interview_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.interviewquestionnaire'),
        ),
        migrations.CreateModel(
            name='WrittenExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('question_file', models.FileField(upload_to='Exam_questions/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainAPP.subject')),
            ],
        ),
        migrations.AddField(
            model_name='examiners',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.writtenexam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.writtenexam'),
        ),
        migrations.AlterUniqueTogether(
            name='examiners',
            unique_together={('exam_id', 'user_id')},
        ),
    ]
