# Generated by Django 5.0.4 on 2024-04-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('otasi', models.CharField(blank=True, max_length=255, null=True)),
                ('jins', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=10)),
                ('telefon_shaxsiy', models.CharField(max_length=13)),
                ('telefon_qoshimcha', models.CharField(blank=True, max_length=13, null=True)),
                ('manzil', models.CharField(max_length=255)),
                ('talim_turi', models.CharField(choices=[('kunduzgi', 'kunduzgi'), ('sirtqi', 'sirtqi')], max_length=255)),
                ('tuman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainAPP.district')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
    ]
