# Generated by Django 5.0.4 on 2024-04-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='manzil',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='talim_turi',
            new_name='education_type',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tuman',
            new_name='region',
        ),
    ]
