# Generated by Django 5.0.4 on 2024-04-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
